version: '3.3'

volumes:
  pg_adv_data:

services:

  db:
    image: postgres:16
    container_name: adv_db
    env_file: .env
    volumes:
      - pg_adv_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: adv_api
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000
    command: ["/app/docker/app.sh"]