"""initial


Revision ID: 3c8bf34129ad
Revises: 
Create Date: 2023-11-01 22:16:24.025199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8bf34129ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('adverts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ad_type', postgresql.ENUM('Продажа', 'Покупка', 'Оказание услуг', name='ad_type'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverts_description'), 'adverts', ['description'], unique=False)
    op.create_index(op.f('ix_adverts_id'), 'adverts', ['id'], unique=False)
    op.create_index(op.f('ix_adverts_title'), 'adverts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adverts_title'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_id'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_description'), table_name='adverts')
    op.drop_table('adverts')
    op.drop_table('users')
    # ### end Alembic commands ###
