"""initial3


Revision ID: b6651440a4b8
Revises: e66f967242bf
Create Date: 2023-11-02 14:02:42.245153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6651440a4b8'
down_revision: Union[str, None] = 'e66f967242bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc',now())"), nullable=False))
    op.alter_column('adverts', 'ad_type',
               existing_type=postgresql.ENUM('Продажа', 'Покупка', 'Оказание услуг', name='ad_type'),
               type_=sa.Enum('Покупка', 'Продажа', 'Оказание услуг', native_enum=False),
               existing_nullable=False)
    op.alter_column('adverts', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('adverts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('adverts_owner_id_fkey', 'adverts', type_='foreignkey')
    op.create_foreign_key(None, 'adverts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adverts', type_='foreignkey')
    op.create_foreign_key('adverts_owner_id_fkey', 'adverts', 'users', ['owner_id'], ['id'])
    op.alter_column('adverts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('adverts', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('adverts', 'ad_type',
               existing_type=sa.Enum('Покупка', 'Продажа', 'Оказание услуг', native_enum=False),
               type_=postgresql.ENUM('Продажа', 'Покупка', 'Оказание услуг', name='ad_type'),
               existing_nullable=False)
    op.drop_column('adverts', 'created_at')
    # ### end Alembic commands ###
