"""initial3


Revision ID: e66f967242bf
Revises: 7b1ac43c4c9f
Create Date: 2023-11-02 00:49:20.078435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66f967242bf'
down_revision: Union[str, None] = '7b1ac43c4c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adverts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('adverts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('adverts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('adverts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
